# Generated by Django 6.0.6 on 2026-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade_nao_urgente',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não Urgente')], default='NAO_URGENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade_urgente',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não Urgente')], default='URGENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status_atrazada',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('ATRASADA', 'Atrasada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='ATRASADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('ATRASADA', 'Atrasada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
