# Generated by Django 6.0.3 on 2026-04-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não Urgente')], default='NAO_URGENTE', max_length=20),
        ),
    ]
