# Generated by Django 6.0.3 on 2026-04-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='buscar',
            field=models.CharField(choices=[('TITULO', 'Título')], default='TITULO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('ATRASADA', 'Atrasada')], default='ABERTA', max_length=20),
        ),
    ]
